import { Providers } from './providers';
import { fonts } from './fonts';

export const metadata = {
  title: 'Welcome to sdm',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <Providers>{children}</Providers>
    </html>
  );
}
